"""leitura: ultimo valor por metrica

Revision ID: 18a733e99f17
Revises: 3e312cfb3978
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '18a733e99f17'
down_revision = '3e312cfb3978'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leitura',
    sa.Column('sujeito', sa.Text(), nullable=False),
    sa.Column('metrica', sa.Text(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('qualidade', sa.String(length=16), server_default=sa.text("'boa'"), nullable=False),
    sa.Column('rotulos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('modulo', sa.Text(), nullable=False),
    sa.Column('em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sujeito', 'metrica')
    )
    op.create_index('ix_leitura_metrica', 'leitura', ['metrica'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_leitura_metrica', table_name='leitura')
    op.drop_table('leitura')
    # ### end Alembic commands ###
