"""esquema inicial: ativos, dispositivos, campos com origem e grafo temporal

Revision ID: 3a994d5b482f
Revises: 
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision = '3a994d5b482f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # A restrição de exclusão da tabela `aresta` compara texto com `=`
    # dentro de um índice GiST, o que exige esta extensão.
    op.execute("CREATE EXTENSION IF NOT EXISTS btree_gist")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achado',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('categoria', sa.String(length=32), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_achado_categoria', 'achado', ['categoria'], unique=False)
    op.create_table('aresta',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('origem_chave', sa.Text(), nullable=False),
    sa.Column('destino_chave', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=32), nullable=False),
    sa.Column('validade', postgresql.TSTZRANGE(), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    postgresql.ExcludeConstraint((sa.column('origem_chave'), '='), (sa.column('destino_chave'), '='), (sa.column('tipo'), '='), (sa.column('validade'), '&&'), using='gist', name='aresta_sem_sobreposicao'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_aresta_destino', 'aresta', ['destino_chave', 'tipo'], unique=False)
    op.create_index('ix_aresta_origem', 'aresta', ['origem_chave', 'tipo'], unique=False)
    op.create_index('ix_aresta_validade', 'aresta', ['validade'], unique=False, postgresql_using='gist')
    op.create_table('ativo',
    sa.Column('ativo_id', sa.Text(), nullable=False),
    sa.Column('frota', sa.Text(), nullable=False),
    sa.Column('numero', sa.Text(), nullable=False),
    sa.Column('site', sa.Text(), server_default=sa.text("'mina'"), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('ativo_id')
    )
    op.create_table('campo',
    sa.Column('sujeito', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('origem', sa.String(length=16), nullable=False),
    sa.Column('natureza', sa.String(length=16), nullable=False),
    sa.Column('valor', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sujeito', 'nome', 'origem')
    )
    op.create_index('ix_campo_sujeito', 'campo', ['sujeito'], unique=False)
    op.create_table('dispositivo',
    sa.Column('chave', sa.Text(), nullable=False),
    sa.Column('nome_bruto', sa.Text(), nullable=False),
    sa.Column('nome_canonico', sa.Text(), nullable=False),
    sa.Column('papel', sa.Text(), nullable=False),
    sa.Column('zona', sa.Text(), nullable=False),
    sa.Column('ativo_id', sa.Text(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativo.ativo_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_index('ix_dispositivo_ativo', 'dispositivo', ['ativo_id'], unique=False)
    op.create_index('ix_dispositivo_papel', 'dispositivo', ['papel'], unique=False)
    op.create_index('ix_dispositivo_zona', 'dispositivo', ['zona'], unique=False)
    op.create_table('identificador',
    sa.Column('dispositivo_chave', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_chave'], ['dispositivo.chave'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('dispositivo_chave', 'tipo', 'valor')
    )
    op.create_index('ix_identificador_busca', 'identificador', ['tipo', 'valor'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_identificador_busca', table_name='identificador')
    op.drop_table('identificador')
    op.drop_index('ix_dispositivo_zona', table_name='dispositivo')
    op.drop_index('ix_dispositivo_papel', table_name='dispositivo')
    op.drop_index('ix_dispositivo_ativo', table_name='dispositivo')
    op.drop_table('dispositivo')
    op.drop_index('ix_campo_sujeito', table_name='campo')
    op.drop_table('campo')
    op.drop_table('ativo')
    op.drop_index('ix_aresta_validade', table_name='aresta', postgresql_using='gist')
    op.drop_index('ix_aresta_origem', table_name='aresta')
    op.drop_index('ix_aresta_destino', table_name='aresta')
    op.drop_table('aresta')
    op.drop_index('ix_achado_categoria', table_name='achado')
    op.drop_table('achado')
    # ### end Alembic commands ###
