"""arranjos de tela

Revision ID: 3e312cfb3978
Revises: e33b86d813aa
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '3e312cfb3978'
down_revision = 'e33b86d813aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arranjo',
    sa.Column('escopo', sa.Text(), nullable=False),
    sa.Column('contexto', sa.String(length=16), nullable=False),
    sa.Column('cartoes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('atualizado_por', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('escopo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arranjo')
    # ### end Alembic commands ###
