"""credencial: cofre de segredos

Revision ID: 720d5d7d520f
Revises: 18a733e99f17
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '720d5d7d520f'
down_revision = '18a733e99f17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credencial',
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=32), nullable=False),
    sa.Column('zona', sa.String(length=32), nullable=False),
    sa.Column('nonce', sa.LargeBinary(), nullable=False),
    sa.Column('segredo', sa.LargeBinary(), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('criada_por', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('nome')
    )
    op.create_index('ix_credencial_zona', 'credencial', ['zona'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_credencial_zona', table_name='credencial')
    op.drop_table('credencial')
    # ### end Alembic commands ###
