"""diagnostico: historico de sondas

Revision ID: 9d760e5c9734
Revises: b95753a51f73
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '9d760e5c9734'
down_revision = 'b95753a51f73'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnostico',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sonda', sa.Text(), nullable=False),
    sa.Column('alvo', sa.Text(), nullable=False),
    sa.Column('sujeito', sa.Text(), nullable=True),
    sa.Column('por', sa.Text(), nullable=False),
    sa.Column('em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duracao_s', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=False),
    sa.Column('resultado', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_diagnostico_sujeito', 'diagnostico', ['sujeito', 'em'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_diagnostico_sujeito', table_name='diagnostico')
    op.drop_table('diagnostico')
    # ### end Alembic commands ###
