"""estado, transicoes e saude de modulo

Revision ID: b465ed04962c
Revises: 3a994d5b482f
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'b465ed04962c'
down_revision = '3a994d5b482f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estado',
    sa.Column('sujeito', sa.Text(), nullable=False),
    sa.Column('alcancavel', sa.Boolean(), nullable=False),
    sa.Column('latencia_ms', sa.Float(), nullable=True),
    sa.Column('perda_pct', sa.Float(), nullable=True),
    sa.Column('jitter_ms', sa.Float(), nullable=True),
    sa.Column('qualidade', sa.String(length=16), server_default=sa.text("'boa'"), nullable=False),
    sa.Column('visto_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sujeito')
    )
    op.create_index('ix_estado_alcancavel', 'estado', ['alcancavel'], unique=False)
    op.create_table('saude_modulo',
    sa.Column('modulo', sa.Text(), nullable=False),
    sa.Column('ultima_coleta_ok', sa.DateTime(timezone=True), nullable=True),
    sa.Column('alvos_total', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('alvos_falha', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('duracao_s', sa.Float(), server_default=sa.text('0'), nullable=False),
    sa.Column('rejeitadas', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('modulo')
    )
    op.create_table('transicao',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sujeito', sa.Text(), nullable=False),
    sa.Column('de', sa.Boolean(), nullable=True),
    sa.Column('para', sa.Boolean(), nullable=False),
    sa.Column('em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transicao_sujeito', 'transicao', ['sujeito', 'em'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transicao_sujeito', table_name='transicao')
    op.drop_table('transicao')
    op.drop_table('saude_modulo')
    op.drop_index('ix_estado_alcancavel', table_name='estado')
    op.drop_table('estado')
    # ### end Alembic commands ###
