"""evento: canal de syslog e trap

Revision ID: b95753a51f73
Revises: 720d5d7d520f
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'b95753a51f73'
down_revision = '720d5d7d520f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evento',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('sujeito', sa.Text(), nullable=True),
    sa.Column('origem_ip', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=16), nullable=False),
    sa.Column('severidade', sa.String(length=16), nullable=False),
    sa.Column('facilidade', sa.String(length=16), server_default=sa.text("''"), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('remetente', sa.Text(), server_default=sa.text("''"), nullable=False),
    sa.Column('confianca', sa.String(length=24), server_default=sa.text("'ip_de_origem'"), nullable=False),
    sa.Column('atributos', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recebido_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evento_recebido', 'evento', ['recebido_em'], unique=False)
    op.create_index('ix_evento_severidade', 'evento', ['severidade', 'recebido_em'], unique=False)
    op.create_index('ix_evento_sujeito', 'evento', ['sujeito', 'recebido_em'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_evento_sujeito', table_name='evento')
    op.drop_index('ix_evento_severidade', table_name='evento')
    op.drop_index('ix_evento_recebido', table_name='evento')
    op.drop_table('evento')
    # ### end Alembic commands ###
