"""contas, sessoes e auditoria

Revision ID: e33b86d813aa
Revises: e94da86d3657
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = 'e33b86d813aa'
down_revision = 'e94da86d3657'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('login', sa.Text(), nullable=True),
    sa.Column('acao', sa.String(length=48), nullable=False),
    sa.Column('sujeito', sa.Text(), nullable=False),
    sa.Column('zona', sa.String(length=24), nullable=True),
    sa.Column('detalhe', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('origem', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_auditoria_em', 'auditoria', ['em'], unique=False)
    op.create_index('ix_auditoria_login', 'auditoria', ['login'], unique=False)
    op.create_index('ix_auditoria_sujeito', 'auditoria', ['sujeito'], unique=False)
    op.create_table('usuario',
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('nome', sa.Text(), nullable=False),
    sa.Column('senha_hash', sa.Text(), nullable=False),
    sa.Column('sal', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ultimo_acesso', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('login')
    )
    op.create_table('concessao',
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('papel', sa.String(length=24), nullable=False),
    sa.Column('zona', sa.String(length=24), nullable=False),
    sa.ForeignKeyConstraint(['login'], ['usuario.login'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('login', 'papel', 'zona')
    )
    op.create_table('sessao',
    sa.Column('resumo', sa.Text(), nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('criada_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('origem', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['login'], ['usuario.login'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('resumo')
    )
    op.create_index('ix_sessao_login', 'sessao', ['login'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sessao_login', table_name='sessao')
    op.drop_table('sessao')
    op.drop_table('concessao')
    op.drop_table('usuario')
    op.drop_index('ix_auditoria_sujeito', table_name='auditoria')
    op.drop_index('ix_auditoria_login', table_name='auditoria')
    op.drop_index('ix_auditoria_em', table_name='auditoria')
    op.drop_table('auditoria')
    # ### end Alembic commands ###
