"""imagens de ativos e dispositivos

Revision ID: e94da86d3657
Revises: b465ed04962c
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = 'e94da86d3657'
down_revision = 'b465ed04962c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imagem',
    sa.Column('sujeito', sa.Text(), nullable=False),
    sa.Column('arquivo', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=32), nullable=False),
    sa.Column('bytes', sa.Integer(), nullable=False),
    sa.Column('largura', sa.Integer(), nullable=True),
    sa.Column('altura', sa.Integer(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('enviado_por', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('sujeito')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imagem')
    # ### end Alembic commands ###
